services:
  postgres:
    image: postgres:16
    container_name: yksdb
    environment:
      POSTGRES_DB: yksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
