-- 1) KONULAR (topic) tablosu
CREATE TABLE IF NOT EXISTS konu (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    ders_id BIGINT NOT NULL REFERENCES ders(id) ON DELETE CASCADE,
    ad VARCHAR(150) NOT NULL,
    UNIQUE (ders_id, ad)
    );

CREATE INDEX IF NOT EXISTS idx_konu_ders ON konu(ders_id);

-- 2) SORU'ya konu_id ekle (önce nullable)
ALTER TABLE soru
    ADD COLUMN IF NOT EXISTS konu_id BIGINT;

-- 3) Eski sorular için her ders’e özel "Genel" konusu oluştur ve ata
DO $$
DECLARE
r RECORD;
  genel_id BIGINT;
BEGIN
FOR r IN (SELECT DISTINCT ders_id FROM soru WHERE konu_id IS NULL)
  LOOP
    INSERT INTO konu(ders_id, ad)
    VALUES (r.ders_id, 'Genel')
    ON CONFLICT (ders_id, ad) DO NOTHING;

SELECT id INTO genel_id FROM konu WHERE ders_id = r.ders_id AND ad = 'Genel';
UPDATE soru SET konu_id = genel_id WHERE ders_id = r.ders_id AND konu_id IS NULL;
END LOOP;
END $$;

-- 4) FK ve zorunluluk
ALTER TABLE soru
    ADD CONSTRAINT IF NOT EXISTS fk_soru_konu
    FOREIGN KEY (konu_id) REFERENCES konu(id) ON DELETE RESTRICT;

CREATE INDEX IF NOT EXISTS idx_soru_konu ON soru(konu_id);

-- Bundan sonra konu_id boş olmamalı (backfill tamamlandıysa güvenle zorunlu yap)
ALTER TABLE soru
    ALTER COLUMN konu_id SET NOT NULL;
